### ISSUE TITLE
ESP32-SX Have alternate partition scheme with no OTA support

### ISSUE THREAD

**Issue by UnexpectedMaker** [adafruit/tinyuf2#227]
Though OTA is cool, I'd hazard to guess that fewer CircuitPython users would use OTA in general, and even be confident enough to guess hardly any use it all.

I'd like to see, not only a second UF2 option for ESP32-SX boards that has no OTA partitions laid out at all, and just a much bigger user file system partition, but also have that be the new default partition layout/binary and have OTA as a second option for those that want to use OTA.

I've spoken a few times with @tannewt about this, and it has to happen at the UF2 bootloader side, as that is what enforces the partition scheme, so we'd need this integrated as alternate builds for ESP32 (and any other platforms that could/might) use this in the future.

I am constantly getting asked questions like... 
<img width="673" alt="Screen Shot 2022-06-25 at 10 43 32 am" src="https://user-images.githubusercontent.com/3156212/175751503-4f9983b0-d35c-4187-9dc4-a1528a9ba40d.png">

or folks just letting me know their board they just received is faulty because it's only got 2MB of flash on it instead of 4MB or 8MB etc like advertised.

I don't really mind how this is implemented - but I think it's really important to give users more flash if it's available on the chip, and the choice to use it or choose OTA instead if that suits their needs.

@hathach Thoughts?

**Comment by Neradoc** [comment]
Note that a solution is now released in Circuitpython 8. This PR: https://github.com/adafruit/circuitpython/pull/7000 thanks to MicroDev, lets you reformat the CIRCUITPY drive so that it extends into the OAT1 partition.
https://docs.circuitpython.org/en/latest/shared-bindings/storage/index.html#storage.erase_filesystem

- An empty flash is formatted in extended mode by default.
- It disables the dualbank module (it's still there but raises an exception).
- Reformatting an existing drive preserves the [non] extended nature of it.

An existing drive can be extended like this (save your data first of course).
```py
import storage
storage.erase_filesystem(extend=True)
```

**Comment by hopkapi** [comment]
Just to be clear, it's actually "extended", rather than "extend":

```
import storage
storage.erase_filesystem(extend=True)
```
